[package]
name = "ru-api-client"
version = "0.1.2"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
url = "2.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2"